# Crowdin Configuration File
# https://support.crowdin.com/configuration-file/

"project_id": "ledger-iframe-bridge"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  [
    {
      "source": "src/locales/en/translation.json",
      "translation": "src/locales/%two_letters_code%/translation.json"
    }
  ]
